// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkjaqbberoxzyzgpgmcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJramFxYmJlcm94enl6Z3BnbWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDI3NzMsImV4cCI6MjA3Mzg3ODc3M30.OjkyZy_WeHvFIbTpYYQLNlBYt2vx6HPwI6vgwgta6jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});